In [20]:
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

In [38]:
A = np.matrix([[2, 1, 1, 3], [1, 0, 1, -1], [1, 1, 0, 4]])
b = np.matrix([[1, 2, 3]]).T

In [39]:
A

matrix([[ 2,  1,  1,  3],
        [ 1,  0,  1, -1],
        [ 1,  1,  0,  4]])

In [40]:
o = sp.linalg.det(A.T * A)
if o == 0:
    print("very bad")
else:
    print("everything is ok, determinant is {}".format(o))

very bad


In [43]:
A_pinv = sp.linalg.pinv(A)

In [42]:
A_pinv =(np.linalg.inv(A.T * A) * A.T ) 

LinAlgError: Singular matrix

In [44]:
A_pinv

array([[ 0.2       ,  0.26666667, -0.06666667],
       [ 0.04444444,  0.02222222,  0.02222222],
       [ 0.15555556,  0.24444444, -0.08888889],
       [ 0.02222222, -0.15555556,  0.17777778]])

In [61]:
x = A_pinv * b

In [62]:
x

matrix([[0.53333333],
        [0.15555556],
        [0.37777778],
        [0.24444444]])

In [63]:
A * x

matrix([[2.33333333],
        [0.66666667],
        [1.66666667]])

In [64]:
print("epsilon is {}".format(sp.linalg.norm(A * x - b)))

epsilon is 2.309401076758503


In [67]:
v = np.matrix([[0, 4, 1, 2]]).T
x = A_pinv * b + v - (A_pinv * A) * v
x

matrix([[-0.6       ],
        [ 3.42222222],
        [ 0.97777778],
        [-0.28888889]])

In [68]:
print("epsilon is {}".format(sp.linalg.norm(A * x - b)))

epsilon is 2.309401076758503
